### ISSUE TITLE
add beauty to CMakeLists.txt

### ISSUE THREAD

**Issue by ronytigo** [dfleury2/beauty#15]
How should I add to CMakeLists.txt?

for rapidyaml I have this for example:
```
add_subdirectory(deps/rapidyaml)
target_include_directories(test PRIVATE deps/rapidyaml/src)
target_link_libraries(test PRIVATE ryml)
```

**Comment by dfleury2** [comment]
If you cloned beauty repo in yout own deps directory ?

May works, but not tested since I used it with conan. You will need to be sure boost and openssl are available.

`
add_subdirectory(deps/beauty)
target_link_libraries(test PRIVATE beauty::beauty)
`

**Comment by ronytigo** [comment]
yes.
I tried that, but now I see I needed to add `set(CONAN OFF)`.
