### ISSUE TITLE
can't get x-www-form-urlencoded params

### ISSUE THREAD

**Issue by ronytigo** [dfleury2/beauty#16]
This is my code:
server.add_route("/person")
        .post([](const auto& req, auto& res) {
            std::istringstream iss(req.body());

            std::string id, name;
            iss >> id >> name;
            std::cout  << id << std::endl;
        });

This is the client call:
```
curl --location --request POST 'http://<ip>:<port>/person' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'id=88' \
--data-urlencode 'name=rrr'
```

it prints `id=88&name=rrr` instead of `88`.

**Comment by dfleury2** [comment]
If you use the form urlencoded, you will need to parse youself the body.
the body received is something like 'id=55&&name=rrr'

To avoid manual parsing, if possible, you can use placeholder, as described in the example:
```
add_route("/person/:id").
.post([](const auto& req, auto& res) {
  // here id is available as an attribute, if requested using url : http;//localhost/person/12345
}
```

Then you can use some parsing (using whatever format you prefer to extract the name).

**Comment by ronytesler** [comment]
How should I make the call so the code in the example will work? I tried different ways.

**Comment by dfleury2** [comment]
Using your C++ code, 

the curl command could be: 
```
curl  -X POST 'http://<ip>:<port>/person' -d '88 rrr'
```

not tested, but should be close to that.

**Comment by ronytesler** [comment]
but the names 'id' and 'name' are not used. do you know the equivalent that should be used in postman?

**Comment by dfleury2** [comment]
Not sure to understand what you try to acheive.

You can either use a GET : `http;//<ip>:<port>/person?id=88&&name=rrr ` with postman.
So the attribut id and name will be available like in the example provided.

or use a POST, and sending whatever body you want to send, like a form encoded or a json format.
in this case you will be to change your C++ code to parse the body.
(either manually or using a json parser)

**Comment by ronytesler** [comment]
but this code is from your example and it's a POST.

**Comment by ronytesler** [comment]
The code is from here:
https://github.com/dfleury2/beauty/blob/79b9f187fa36f2df6cbc75b6ab0afa153e9ff946/examples/server.cpp

So the example is not working?

**Comment by dfleury2** [comment]
yes, it's working but I choose to use a simple format to send the id and the name (just a line like '88 rrr')
 So in POSTMAN, just use a POST and just put `88 rrr` in the body.
 If you want something more fany, you can use a json format, and update the example to parse the body (so the id and the name wil appear and will be used)
But this was not the purpose of the example here.

**Comment by ronytesler** [comment]
ah ok, I thought the call should pass 'id' and 'name'. I'll look for a json parser.
