### ISSUE TITLE
beauty is beautiful!

### ISSUE THREAD

**Issue by ghost** [dfleury2/beauty#2]
hi dev, just came here to say thanks for developing this awesome library. glad to be here and creating the first issue before it become famous! i'm currently using it in production and it works like a charm.

**Comment by nklii** [comment]
btw, could you give me your email address? we may have some works in future.

**Comment by dfleury2** [comment]
Hi,
sorry it seems, I did not receive notifications...
Thanks for the proposal, but I am not available at this time ;)

**Comment by dfleury2** [comment]
In case you found a bug, do not hesitate to report it, or event better fix it ;)
