### ISSUE TITLE
Unable to send https request

### ISSUE THREAD

**Issue by blldce** [dfleury2/beauty#25]
Hi,
Currently client can able to send "http" requests (ie. http://httpbin.org/get), but can not able to send "https" requests (ie. https://httpbin.org/get)

Is this a bug or something I missed?

Thank you

**Comment by dfleury2** [comment]
Hi,
you can look at the beauty_client_.... _ssl.cpp in the examples.
It's fine to use beauty client with https requests. It was use a lot already with https (using openssl)
Regards,
