### ISSUE TITLE
streaming big files

### ISSUE THREAD

**Issue by muninnan** [dfleury2/beauty#31]
Hi,
I'm trying your great project for my app, but I didn't find example on how to upload/download big files(eg. GB level)
could you please give me an example or some idea to do it with this project?

**Comment by dfleury2** [comment]
Hi,
I am not sure what do you mean by streaming. HTTP is not for stream IMO, so may be it's about the WebSocket part ?
I do not set any limitation on file size, but the create of Beast, if I remember well, said that if you need to transfertbig files, HTTP if not the best techno to use.

Anyway, if you want to stream data, you can still send chunk over a predefined protocol, so the client can glue the chunk together.

Regards,

**Comment by muninnan** [comment]
thanks for your suggestion, chunked transfer sounds a good idea
