### ISSUE TITLE
Https & certs

### ISSUE THREAD

**Issue by Romain-P** [dfleury2/beauty#38]
I’m exploring the use of Beauty as an HTTP(S) client;

Does Beauty currently support using the trusted CA store of the underlying system (e.g., the Windows certificate store) for server certificate validation? If not, would it be feasible to add this support, and how much effort would it require?

Additionally, I’m interested in implementing certificate pinning in the client, specifically using the sha256// format for pins. Could you provide some guidance on how complex it would be to integrate this feature within Beauty?

I’d appreciate any insights or recommendations you might have regarding these use cases.

**Comment by dfleury2** [comment]
Hi,
the certificat part is done by Boost::Beast. I do not know what will be necessary to provide this support. 
May be you can look at Beast code if something was done for this feature. 
Regards,
