### ISSUE TITLE
Not able to disable conan install method

### ISSUE THREAD

**Issue by dhruvkakadiya** [dfleury2/beauty#6]
In readme, seems minor typo.

> replace cmake .. -DCMAKE_BUILD_TYPE=Release by cmake .. -DCMAKE_BUILD_TYPE=Release -DCONAN_false to not use Conan. Hope your the dependencies are found on your Linux.

which can be
> replace cmake .. -DCMAKE_BUILD_TYPE=Release by cmake .. -DCMAKE_BUILD_TYPE=Release -DCONAN=false to not use Conan. Hope your the dependencies are found on your Linux.

Even though correcting that, cmake toolchain try to find `conan` so it's trying to install this library through conan.. so seems like disabling conan not working as expected.

While digging through root level `CMakeLists.txt` file, below can be found so probably that needs to be taken under `CONAN` macro which worked fine for me. Also didn't understand use case of empty `CONAN_EXPORTED`.

```cmake
if (CONAN_EXPORTED)
else()
    if (NOT EXISTS ${CMAKE_BINARY_DIR}/conan_toolchain.cmake)
        include(${PROJECT_SOURCE_DIR}/cmake/conan.cmake)

        conan_cmake_autodetect(settings)

        conan_cmake_install(PATH_OR_REFERENCE ${PROJECT_SOURCE_DIR}/conanfile.py
                PROFILE ${CONAN_PROFILE}
                PROFILE_BUILD ${CONAN_PROFILE}
                BUILD missing
                SETTINGS ${settings}
                )
    endif()
endif()

include(${CMAKE_BINARY_DIR}/conan_toolchain.cmake)
```

which can be
```cmake
if (CONAN)
    if (NOT EXISTS ${CMAKE_BINARY_DIR}/conan_toolchain.cmake)
        include(${PROJECT_SOURCE_DIR}/cmake/conan.cmake)

        conan_cmake_autodetect(settings)

        conan_cmake_install(PATH_OR_REFERENCE ${PROJECT_SOURCE_DIR}/conanfile.py
                PROFILE ${CONAN_PROFILE}
                PROFILE_BUILD ${CONAN_PROFILE}
                BUILD missing
                SETTINGS ${settings}
                )
    else()
        include(${CMAKE_BINARY_DIR}/conan_toolchain.cmake)
    endif()
endif()
```

**Comment by dfleury2** [comment]
Hi,
Thanks I will fix this part when conan is not used.

**Comment by dfleury2** [comment]
Done.
You can try the lastest commits, should work without Conan.

**Comment by dhruvkakadiya** [comment]
Thank you, @dfleury2.
