### ISSUE TITLE
http server question

### ISSUE THREAD

**Issue by Arnold1** [dfleury2/beauty#7]
Hi,

I want to use your http server in an app. how can I integrate it with my bazel build?

Also, what json library do you suggest to parse the incoming http request and create the http resonse?

Thanks

**Comment by dfleury2** [comment]
Hi,
I do not know Bazel at all. Conan has a page for it : https://docs.conan.io/en/1.46/integrations/build_system/bazel.html
But it's not very clear how to integrate a dependency when you do not know Bazel. I will see if I can make an example for Bazel quickly.

For json, I use only nlohmann json (https://github.com/nlohmann/json)
I have tried Boost.Json too but I prefer the first one for now.

Regards,

**Comment by dfleury2** [comment]
Here, you have an example that download the package from conan-center, and use it to create a server.

[Bazel example](https://github.com/dfleury2/beauty/tree/master/examples/bazel)

I let you do the json integration ;)

**Comment by Arnold1** [comment]
hi @dfleury2 thanks. it looks like i need to also install conan - is there a way to do it without conan and just use bazel? I see you have a make in the project - shouldn't that be enough?

**Comment by dfleury2** [comment]
Hi,
I do not know bazel enough. Not sure I want to learn it, it's kind of unusual build system for C++.
I will not know how to do it, but clearly it should be possible.

The dependencies missing is generated using the conan command. I have successfully build the server example while consuming the beauty package from conan center using only the command in the README.md of the bazel directory.

If there is only one thread for the io_context, no need for mutex. The same thread will be used for reading and writing from http request.

**Comment by Arnold1** [comment]
also can I compile your library with c++17? - it seems I cant switch to c++20 yet...

**Comment by dfleury2** [comment]
Depends on your compiler.
Visual Studio 2019 need to C++20 flag, May be Visual Studio 2022.
For gcc C++17 is enough and at least gcc8 (works fine with gcc10 and gcc11)

**Comment by Arnold1** [comment]
my current bazel project needs c++17 ... I have g++ under ubuntu 22.04

**Comment by dfleury2** [comment]
I do not use Ubuntu.  What give the command `gcc --version` ?

**Comment by Arnold1** [comment]
```gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0```

**Comment by dfleury2** [comment]
Pretty descent one. Good :)
This should work fine using only c++17 flag

**Comment by Arnold1** [comment]
getting:

```
ERROR: /home/developer/tmp/examples2/standalone/BUILD.bazel:6:10: Linking beginner_cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/beginner_cc-2.params
bazel-out/k8-opt/bin/_objs/beginner_cc/beginner.o:beginner.cc:function main: error: undefined reference to 'beauty::server::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (beauty::request const&, beauty::response&)>&&)'
bazel-out/k8-opt/bin/_objs/beginner_cc/beginner.o:beginner.cc:function main: error: undefined reference to 'beauty::server::listen(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
Target //:beginner_cc failed to build
```

for:
```
 // ...
 // ...

// Create a server
  beauty::server server;

  // '/person'
  server.add_route("/person")
        // Get the list of available ids
        .get([](const auto& req, auto& res) {
            for (const auto& [id, _] : storage) {
                res.body() += id + "\n";
            }
        });

  // Open the listening port
    server.listen(8085);

    // Run the event loop - Warning, add a new thread (to be updated may be)
    server.run();  // or server.wait(); for no supplementary thread

  return 0;
```

**Comment by dfleury2** [comment]
This is a link error. You can try to installe the package with '-b beauty' instead of '-b missing' so it compile the lib with your profile.

You can remove `return 0;` this is not mandatory for the main (the correct value should be return EXIT_SUCCESS or something like that, so better to not put a return at all).

Another option, if you know Bazel, is to get the source from github tag, and create the lib locally in your bazel project, 
or create a lib with bazel so you can use it in your own projects.

**Comment by Arnold1** [comment]
I tried:
```
 conan install . -pr default -pr:b default -b beauty -r conancenter
```

still get:
```
ERROR: /home/developer/tmp/examples2/standalone/BUILD.bazel:6:10: Linking beginner_cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/beginner_cc-2.params
bazel-out/k8-opt/bin/_objs/beginner_cc/beginner.o:beginner.cc:function main: error: undefined reference to 'beauty::server::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (beauty::request const&, beauty::response&)>&&)'
bazel-out/k8-opt/bin/_objs/beginner_cc/beginner.o:beginner.cc:function main: error: undefined reference to 'beauty::server::listen(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
Target //:beginner_cc failed to build
```

**Comment by dfleury2** [comment]
Are you sure that the beauty lib is used during the link step ?
Do you have a way to see what command is used by bazel to compile and link your example ?

**Comment by Arnold1** [comment]
BUILD.bazel:
```
package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

cc_binary(
    name = "beginner_cc",
    srcs = ["beginner.cc"],
    deps = [
        // ... other stuff
        "@beauty//:beauty",
    ],
)
```

```
bazel build --config=linux_cpp17 --config=linux_avx2 //:beginner_cc
```

**Comment by dfleury2** [comment]
I meant the underlying gcc command used by bazel

**Comment by Arnold1** [comment]
I see its trying to use:
```
external/beauty/lib/libbeauty.a
```

**Comment by dfleury2** [comment]
Everything seems fine.
Not sure to understand why the linker did not find the server methods.
Can you try to error/retry steps by removing the get and listen, steps by step ?

Or may be check the difference with my example that works under Debian Bullseye ?

**Comment by Arnold1** [comment]
whats the diff between:
```
 conan install . -pr default -pr:b default -b beauty -r conancenter
```

and:
```
 conan install . -pr default -pr:b default -b default -r conancenter
```

**Comment by dfleury2** [comment]
-b beauty will always build beauty locally,
-b missing will build only the missing dependency for the `default` profile.

**Comment by Arnold1** [comment]
I can create a repo with the test code :)

**Comment by dfleury2** [comment]
yeah, do it.  I will see later if I make it work.  Not sure when, this is work days now ;)

**Comment by Arnold1** [comment]
@dfleury2 code is here:
https://github.com/Arnold1/yggdrasil-decision-forests-with-server
run: ./build.sh ./run.sh

than run:
https://github.com/Arnold1/yggdrasil-decision-forests-with-server/blob/main/yggdrasil-decision-forests/examples_with_server/standalone/compile_and_run.sh

for: https://github.com/Arnold1/yggdrasil-decision-forests-with-server/tree/main/yggdrasil-decision-forests/examples_with_server/standalone

**Comment by Arnold1** [comment]
does that help to run it?

**Comment by dfleury2** [comment]
Just try to build the image, but took too long here. I will try tomorow.
But clearly, the docker image is a good way to go. Thanks.
If you find something let me now. I will see if I can make something tomorrow, but my working days are pretty overloaded.

**Comment by Arnold1** [comment]
@dfleury2 thanks so much - looking forward :)

**Comment by Arnold1** [comment]
@dfleury2 i fixed the docker image: 
https://github.com/Arnold1/yggdrasil-decision-forests-with-server
